# .bash_profile

EDITOR=micro
if [ -f ~/.bashrc ]; then 
	. ~/.bashrc 
fi

# Set Path for USER Programs
export GOPATH="$HOME/go"
export PATH="$PATH:$GOPATH/bin"
export PATH="$PATH:$HOME/.config/emacs/bin"

# Set path for brew
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

# Added by Toolbox App
export PATH="$PATH:/home/aaditya/.local/share/JetBrains/Toolbox/scripts"
. "$HOME/.cargo/env"
