# .bash_profile

EDITOR=micro
if [ -f ~/.bashrc ]; then 
	. ~/.bashrc 
fi

# Set Path for USER Programs

# Path for Toolbox
export PATH="$HOME/.local/share/JetBrains/Toolbox/scripts:$PATH"
# Set path for brew
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
